# schedules:
# - cron: "0 0 * * *"
#   displayName: Daily midnight cleanup
#   branches:
#     include:
#     - master

#trigger: none
trigger:
  batch: true
  branches:
    include:
      - feature/7969-clear-old-environments
  paths:
    include:
      - housekeeping/*

pr: none

jobs:
  - job: getWorkitems
    displayName: Get all work items
    steps:
    - task: queryWorkItems@0
      inputs:
        queryId: '00f85790-b1dd-4e36-b4ee-3e8873b1478b'
        maxThreshold: '1000' 
        #minThreshold: '0' 