apiVersion: v2
name: buyingcatalogue
description: A Helm chart for Kubernetes
icon: https://digital.nhs.uk/webfiles/1583237303085/images/nhs-digital-logo.svg
# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
version: 0.1.0

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application.
appVersion: 0.1.0

dependencies:
- name: azurite
  condition: azurite.enabled
  version: ~0.1.0
- name: bapi
  condition: bapi.enabled
  version: ~0.1.0
- name: bapi-db
  condition: bapi-db.enabled
  version: ~0.1.0
- name: dapi
  condition: dapi.enabled
  version: ~0.1.0
- name: isapi
  condition: isapi.enabled
  version: ~0.1.0
- name: isapi-db
  condition: isapi-db.enabled
  version: ~0.1.0
- name: oapi
  condition: oapi.enabled
  version: ~0.1.0
- name: ordapi
  condition: ordapi.enabled
  version: ~0.1.0
- name: ordapi-db
  condition: ordapi-db.enabled
  version: ~0.1.0
- name: email
  condition: email.enabled
  version: ~0.1.0
- name: file-loader
  condition: file-loader.enabled
  version: ~0.1.0
- name: mp
  condition: mp.enabled
  version: ~0.1.0
- name: pb
  condition: pb.enabled
  version: ~0.1.0
- name: admin
  condition: admin.enabled
  version: ~0.1.0-alpha 
  repository: "https://gpitfuturesdevacr.azurecr.io/helm/v1/repo"
- name: of
  condition: of.enabled
  version: ~0.1.0
- name: redis
  condition: redis.enabled
  version: ~10.6.7
  repository: "https://charts.bitnami.com/bitnami"
- name: redis-commander
  condition: redis-commander.enabled
  version: ~0.1.0