apiVersion: v2
name: buyingcatalogue
description: A Helm chart for Kubernetes
icon: https://digital.nhs.uk/webfiles/1583237303085/images/nhs-digital-logo.svg
# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
version: 0.1.0

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application.
appVersion: 0.1.0

dependencies:
- name: azurite
  condition: azurite.enabled
  version: ~0.1.0
- name: db
  condition: db.enabled
  version: ~0.1.0
- name: bapi-db-deploy
  condition: bapi-db-deploy.enabled
  version: 2.0.23-PullRequest0320.2
  repository: "@gpitfuturesdevacr"
- name: bapi
  condition: bapi.enabled
  version: 2.0.23-PullRequest0320.2
  repository: "@gpitfuturesdevacr"
- name: dapi
  condition: dapi.enabled
  version: 2.0.1
  repository: "@gpitfuturesdevacr"
- name: isapi
  condition: isapi.enabled
  version: 1.33.0-alpha.6
  repository: "@gpitfuturesdevacr"
- name: isapi-db-deploy
  condition: isapi-db-deploy.enabled
  version: 1.33.0-alpha.6
  repository: "@gpitfuturesdevacr"
- name: oapi
  condition: oapi.enabled
  version: 1.33.0-alpha.6
  repository: "@gpitfuturesdevacr"
- name: ordapi
  condition: ordapi.enabled
  version: 2.0.20
  repository: "@gpitfuturesdevacr"
- name: ordapi-db-deploy
  condition: ordapi-db-deploy.enabled
  version: 2.0.20
  repository: "@gpitfuturesdevacr"
- name: email
  condition: email.enabled
  version: 1.24.8
  repository: "@gpitfuturesdevacr"
- name: file-loader
  condition: file-loader.enabled
  version: 2.0.1
  repository: "@gpitfuturesdevacr"
- name: mp
  condition: mp.enabled
  version: 2.0.4
  repository: "@gpitfuturesdevacr"
- name: pb
  condition: pb.enabled
  version: 2.0.5
  repository: "@gpitfuturesdevacr"
- name: admin
  condition: admin.enabled
  version: 2.0.3
  repository: "@gpitfuturesdevacr"
- name: of
  condition: of.enabled
  version: 1.38.1-alpha.182
  repository: "@gpitfuturesdevacr"
- name: redis
  condition: redis.enabled
  version: ~10.6.7
  repository: "https://charts.bitnami.com/bitnami"
- name: redis-commander
  condition: redis-commander.enabled
  version: ~0.1.0
- name: pb-ac-tests
  condition: pb-ac-tests.enabled
  version: 2.0.1
  repository: "@gpitfuturesdevacr"
- name: mp-ac-tests
  condition: mp-ac-tests.enabled
  version: 2.0.2
  repository: "@gpitfuturesdevacr"
- name: admin-ac-tests
  condition: admin-ac-tests.enabled
  version: 2.1.0
  repository: "@gpitfuturesdevacr"
- name: of-ac-tests
  condition: of-ac-tests.enabled
  version: 2.0.0
  repository: "@gpitfuturesdevacr"
- name: allure
  condition: allure.enabled
  version: ~0.1.0
