{{- $dbUrl:= ternary (printf "%s.%s" (include "call-nested" (list . "db" "db.fullname")) .Release.Namespace) (default "NotSet" .Values.db.disabledUrl) .Values.db.enabled -}}
{{- $dapiUrl:= ternary (printf "%s.%s" (include "call-nested" (list . "dapi" "dapi.fullname")) .Release.Namespace) (default "NotSet" .Values.dapi.disabledUrl) .Values.dapi.enabled -}}
{{- $bapiUrl:= ternary (printf "%s.%s" (include "call-nested" (list . "bapi" "bapi.fullname")) .Release.Namespace) (default "NotSet" .Values.bapi.disabledUrl) .Values.bapi.enabled -}}
{{- $oapiUrl:= ternary (printf "%s.%s" (include "call-nested" (list . "oapi" "oapi.fullname")) .Release.Namespace) (default "NotSet" .Values.oapi.disabledUrl) .Values.oapi.enabled -}}
{{- $ordapiUrl:= ternary (printf "%s.%s" (include "call-nested" (list . "ordapi" "ordapi.fullname")) .Release.Namespace) (default "NotSet" .Values.ordapi.disabledUrl) .Values.ordapi.enabled -}}
{{- $isapiUrl:=  ternary (printf "http://%s.%s:%d/%s" (include "call-nested" (list . "isapi" "isapi.fullname")) .Release.Namespace (.Values.isapi.service.port | int ) .Values.isapi.pathBase) (default "NotSet" .Values.isapi.disabledUrl) .Values.isapi.enabled -}}
{{- $isapiIssuerUrl:= ternary .Values.baseIsapiEnabledUrl (default "NotSet" .Values.isapi.disabledUrl) .Values.isapi.enabled -}}
{{- $adminUrl:= ternary .Values.admin.baseUri (default "NotSet" .Values.admin.disabledUrl) .Values.admin.enabled -}}
{{- $ofUrl:= ternary (printf "%s/" .Values.of.baseUri) (default "NotSet" .Values.of.disabledUrl) .Values.of.enabled -}}
{{- $pbUrl:= ternary .Values.pb.baseUri (default "NotSet" .Values.pb.disabledUrl) .Values.pb.enabled -}}
{{- $emailUrl:= ternary (printf "%s.%s" (include "call-nested" (list . "email" "email.fullname")) .Release.Namespace) (default "NotSet" .Values.email.disabledUrl) .Values.email.enabled -}}
{{- $redisUrl:= ternary (printf "%s-master" (include "call-nested" (list . "redis" "redis.fullname"))) (default "NotSet" .Values.redis.disabledUrl) .Values.redis.enabled -}}
{{- $container:= default (printf "%s-documents" .Release.Namespace) .Values.containerName -}}

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "buyingcatalogue.fullname" . }}
  labels:     
    {{- include "buyingcatalogue.labels" . | nindent 4 }}
data:
  db-url: {{ $dbUrl | quote }}
  db-port: {{ .Values.db.service.port | quote }}
  dapi-url: {{ printf "http://%s:%d" $dapiUrl (.Values.dapi.service.port | int ) }}
  bapi-url: {{ printf "http://%s:%d" $bapiUrl (.Values.bapi.service.port | int ) }}
  oapi-url: {{ printf "http://%s:%d" $oapiUrl (.Values.oapi.service.port | int ) }}
  ordapi-url: {{ printf "http://%s:%d" $ordapiUrl (.Values.ordapi.service.port | int ) }}  
  isapi-url: {{  $isapiUrl | quote }}  
  issuer-url: {{  $isapiIssuerUrl | quote }}  
  admin-url: {{  $adminUrl | quote }}
  of-url: {{  $ofUrl | quote }}
  app-base-url: {{ .Values.appBaseUrl }}
  email-url: {{ $emailUrl | quote }}  
  redis-url: {{ $redisUrl | quote }}
  pb-url: {{  $pbUrl | quote }}
  document-container: {{ $container | quote }}