{{- $saPassword := randAlphaNum 20 -}}
{{- $dbPassword := default (randAlphaNum 20) .Values.dbPassword -}}
{{- $clientSecret := default (randAlphaNum 10) .Values.clientSecret -}}
{{- $eaUserPassword := randAlphaNum 20 -}}
{{- $redisPassword := randAlphaNum 10 -}}

{{- $bapiDbValues:= index .Values "bapi-db" -}} #work around for chart naming convention clash - https://github.com/helm/helm/issues/2192
{{- $bapiSqlName:= ternary (printf "%s.%s" (include "call-nested" (list . "bapi-db" "bapi-db.fullname")) .Release.Namespace) $bapiDbValues.disabledUrl $bapiDbValues.enabled }}
{{- $bapiSqlServer := printf "%s,%d" $bapiSqlName ( $bapiDbValues.service.port | int) -}}

{{- $isapiDbValues:= index .Values "isapi-db" -}} #work around for chart naming convention clash - https://github.com/helm/helm/issues/2192
{{- $isapiSqlName:= ternary (printf "%s.%s" (include "call-nested" (list . "isapi-db" "isapi-db.fullname")) .Release.Namespace) $isapiDbValues.disabledUrl $isapiDbValues.enabled }}
{{- $isapiSqlServer := printf "%s,%d" $isapiSqlName ( $isapiDbValues.service.port | int) -}}


{{- $ordapiDbValues:= index .Values "ordapi-db" -}} #work around for chart naming convention clash - https://github.com/helm/helm/issues/2192
{{- $ordapiSqlName:= ternary (printf "%s.%s" (include "call-nested" (list . "ordapi-db" "ordapi-db.fullname")) .Release.Namespace) $ordapiDbValues.disabledUrl $ordapiDbValues.enabled }}
{{- $ordapiSqlServer := printf "%s,%d" $ordapiSqlName ( $ordapiDbValues.service.port | int) -}}

{{- $azureblobAccountName:= "devstoreaccount1" -}}
{{- $azureblobAccountKey:= "Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==" -}}
{{- $azureblobPort:= .Values.azurite.service.blobPort | int }}
{{- $azureblobQueuePort:= .Values.azurite.service.queuePort | int }}
{{- $azureblobTablePort:= .Values.azurite.service.tablePort | int }}
{{- $azureblobUrl:= ternary (printf "%s.%s" (include "call-nested" (list . "azurite" "azurite.fullname")) .Release.Namespace) .Values.azurite.disabledUrl .Values.azurite.enabled }}

apiVersion: v1
kind: Secret
metadata:
  name: {{ template "buyingcatalogue.fullname" . }}
  labels:     
    {{- include "buyingcatalogue.labels" . | nindent 4 }}
type: Opaque
data:  
  sa-password: {{ $saPassword | b64enc | quote }}  
  db-password: {{ $dbPassword | b64enc | quote }}
  azure-blob-connection-string: {{ printf "AccountName=%s;AccountKey=%s;DefaultEndpointsProtocol=http;BlobEndpoint=http://%s:%d/%s;QueueEndpoint=http://%s:%d/%s;TableEndpoint=http://%s:%d/%s;" $azureblobAccountName $azureblobAccountKey $azureblobUrl $azureblobPort $azureblobAccountName $azureblobUrl $azureblobQueuePort $azureblobAccountName $azureblobUrl $azureblobTablePort $azureblobAccountName | b64enc | quote }}
  bapi-db-connection-string: {{ printf "Server=%s;Initial Catalog=%s;Persist Security Info=False;User Id=%s;Password=%s" $bapiSqlServer $bapiDbValues.dbName $bapiDbValues.dbUser $dbPassword | b64enc | quote }}
  isapi-db-connection-string: {{ printf "Server=%s;Initial Catalog=%s;Persist Security Info=False;User Id=%s;Password=%s" $isapiSqlServer $isapiDbValues.dbName $isapiDbValues.dbUser $dbPassword | b64enc | quote }}
  ordapi-db-connection-string: {{ printf "Server=%s;Initial Catalog=%s;Persist Security Info=False;User Id=%s;Password=%s" $ordapiSqlServer $ordapiDbValues.dbName $ordapiDbValues.dbUser $dbPassword | b64enc | quote }}
  oidc-client-secret:  {{ $clientSecret | b64enc | quote }}  
  cookie-secret : {{ .Values.cookieSecret | default "secret squirrel" | b64enc | quote }}
  ea-user-password: {{ $eaUserPassword | b64enc | quote }}  
  redis-password: {{ $redisPassword | b64enc | quote }}  
