apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bc-test-result-pvc
spec:
  storageClassName: {{ .Values.testStorage.storageClassName }}
  accessModes:
    - {{ .Values.testStorage.accessMode }}
  resources:
    requests:
      storage: 1Gi
