{{- if .Values.localTestResultStorage.enabled -}}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: bc-test-result-pv
  labels:
    type: local
spec:
  storageClassName: hostpath
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/buyingcatalogue/test"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bc-test-result-local-pvc
spec:
  storageClassName: hostpath
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
{{- end }}