{{- $className:= ternary "hostpath" "azurefile" .Values.useLocalTestResultStorage | quote -}}
{{- $accessMode:= ternary "ReadWriteOnce" "ReadWriteMany" .Values.useLocalTestResultStorage | quote -}}

{{- if .Values.useLocalTestResultStorage -}}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: bc-test-result-pv
  labels:
    type: local
spec:
  storageClassName: hostpath
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/buyingcatalogue/test"
---
{{- end }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bc-test-result-pvc
spec:
  storageClassName: {{ $className }}
  accessModes:
    - {{ $accessMode }}
  resources:
    requests:
      storage: 1Gi
