global:  
  nodeSelector:
  #  label: value
  ## Configure HostAliases
  hostAliases: []
  affinity:
  #  label: value
  tolerations:
  #  label: value
  ## imagePullSecrets is the secret to use to pull the image from in case of a private flavour image
  ## to be used in every deployment hub, chrome, firefox, chromeDebug and firefoxDebug
  ## can also be specified at chart level see below.
  ## Specifying secret at a chart level will override the global option
  imagePullSecrets:

hub:  
  image: "selenium/hub"
  ## ref: https://hub.docker.com/r/selenium/hub/tags/
  tag: "3.141.59"  
  pullPolicy: Always
  port: 4444
  servicePort: 4444
  readinessTimeout: 1
  readinessDelay: 15
  livenessTimeout: 1
  probePath: "/wd/hub/status"
  extraEnvs: []
  javaOpts: "-Xmx1000m"
  resources:
    requests:
      cpu: ".25"
      memory: "250Mi"
    limits:
      cpu: ".5"
      memory: "1000Mi"  
  podAnnotations: {}
  serviceType: "LoadBalancer"
  loadBalancerSourceRanges: []
  serviceSessionAffinity: "None"
  nodeSelector:
  #  label: value
  ingress:
    enabled: false
    annotations: {}
    path: /
    hosts:
      - selenium-hub.local
    tls: []

chrome:  
  enabled: true
  image: "selenium/node-chrome"
  tag: "3.141.59"
  pullPolicy: Always
  replicas: 4
  javaOpts: "-Xmx1000m"
  volumes:
    - name: dshm
      emptyDir:
        medium: Memory
  volumeMounts:
    - mountPath: /dev/shm
      name: dshm
  resources:
    requests:
      cpu: ".25"
      memory: "250Mi"
    limits:
      cpu: "1"
      memory: "1000Mi"

  ## Characteristics of the browser window
  # screenWidth: 1280
  # screenHeight: 1024
  # screenDepth: 24
  # display: :10

  ## Selenium node options
  # chromeVersion:
  nodeMaxInstances: 2
  nodeMaxSession: 2
  ## In milliseconds
  # nodeRegisterCycle: 5000
  # nodePort: 5555
  # timeZone: UTC

  ## NodeSelector to be used for chrome
  nodeSelector:
  #  label: value

firefox:
  enabled: false
  image: "selenium/node-firefox"
  tag: "3.141.59"
  pullPolicy: Always
  replicas: 4
  javaOpts: "-Xmx1000m"
  resources:
    requests:
      cpu: ".25"
      memory: "250Mi"
    limits:
      cpu: ".5"
      memory: "1000Mi"

  ## Characteristics of the browser window
  # screenWidth: 1280
  # screenHeight: 1024
  # screenDepth: 24
  # display: :10

  ## Selenium node options
  # firefoxVersion:
  nodeMaxInstances: 2
  nodeMaxSession: 2
  ## In milliseconds
  # nodeRegisterCycle: 5000
  # nodePort: 5555
  # timeZone: UTC

  ## NodeSelector to be used for firefox
  nodeSelector:
  #  label: value